[workspace]
resolver = "3"
members = [
  "imbuf",
  "imbuf-opencv",
]

[workspace.package]
authors = ["mineichen"]
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/mineichen/imbuf"

[workspace.dependencies]
imbuf = { path = "imbuf", version = "0.3.3" }
imbuf-opencv = { path = "imbuf-opencv", version = "0.1.0" }
log = "0.4"
testresult = "0.4"
thiserror = "2"
